services:
  # --------------------------------------------
  # MOSQUITTO -----------------------------------
  # --------------------------------------------
  broker:
    container_name: mosquitto-container
    hostname: mosquittoName
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - net-test
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  # --------------------------------------------
  # NODERED -----------------------------------
  # --------------------------------------------
  nodered:
    container_name: nodered-container
    image: nodered/node-red:latest
    hostname: nodeName
    ports:
      - "1880:1880"
    networks:
      - net-test
    volumes:
      - ./nodered:/data
    depends_on:
      - broker

  # --------------------------------------------
  # INFLUXDB -----------------------------------
  # --------------------------------------------
  influxdb:
    container_name: influxdb-container
    build:
      context: ./influxdb
    hostname: influxdbName
    ports:
      - "8086:8086"
    networks:
      - net-test
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    depends_on:
      - broker

  # --------------------------------------------
  # SENSORS -----------------------------------
  # --------------------------------------------
  sensors:
    build: ./sensors/
    hostname: sensorsName
    networks:
      - net-test
    depends_on:
      - broker
      - nodered

networks:
  net-test:
    driver: bridge

volumes:
  nodered:
  mosquitto:
  influxdb: