services:
  # --------------------------------------------
  # MOSQUITO -----------------------------------
  # --------------------------------------------
  # mosquitto will be the MQTT broker
  broker:
    container_name: mosquitto-container
    hostname: mosquittoName
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
          - net-test
    volumes:
          - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
          - ./log:/mosquitto/log

  # --------------------------------------------
  # NODERED -----------------------------------
  # --------------------------------------------
  nodered:
    #build: ./nodered/
    container_name: nodered-container
    image: nodered/node-red:latest
    hostname: nodeName
    ports:
      - "1880:1880"
    networks:
          - net-test
    volumes:
      - data:/data
      - ./flows.json:/data/flows.json


  # --------------------------------------------
  # SENSORS -----------------------------------
  # --------------------------------------------
  sensors:
     build: ./sensors/
     hostname: sensorsName
     networks:
           - net-test
  # reconfiguration idea:
      # 1) turn off the system
      # 2) Wirte the new java class for the sensors
      # 3) add it to the script that runs the sensors
      # 4) docker compose up the system

  # --------------------------------------------
  # ACTUATORS -----------------------------------
  # --------------------------------------------
#  actuators:
#    build: ./actuators/
#    networks:
#          - net-test

volumes:
  data:
  conf:
  logs:

networks:
  net-test:
    driver: bridge  
