services:
  # --------------------------------------------
  # MOSQUITO -----------------------------------
  # --------------------------------------------
  # mosquitto will be the MQTT broker
  broker:
    container_name: mosquitto-container
    hostname: mosquittoName
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
          - net-test
    volumes:
          - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  # --------------------------------------------
  # NODERED -----------------------------------
  # --------------------------------------------
  nodered:
    container_name: nodered-container
    image: nodered/node-red:latest
    hostname: nodeName
    ports:
      - "1880:1880"
    networks:
          - net-test
    volumes:
      - ./nodered:/data
    depends_on:
      - broker


  # --------------------------------------------
  # SENSORS -----------------------------------
  # --------------------------------------------
  sensors:
     build: ./sensors/
     hostname: sensorsName
     networks:
           - net-test
     depends_on:
      - broker
      - nodered

      # NOTE: reconfiguration idea:
      # 1) turn off the system
      # 2) Wirte the new java class for the sensors
      # 3) add it to the script that runs the sensors
      # 4) docker compose up the system

  # --------------------------------------------
  # ACTUATORS -----------------------------------
  # --------------------------------------------
#  actuators:
#    build: ./actuators/
#    networks:
#          - net-test

volumes:
  nodered:
  mosquitto:

networks:
  net-test:
    driver: bridge  
