services:
  broker-mosquitto:
    build: ./brokerMqtt/
    ports:
      - "1883:1883"
    networks:
          - mqtt-network
  client-java:
    build: ./clientMqtt/
    networks:
          - mqtt-network
networks:
  mqtt-network:
    driver: bridge
