services:
  broker:
    image: eclipse-mosquitto  
    ports:
      - "1883:1883"
    networks:
          - nodered-mosquitto
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./log:/mosquitto/log
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest 
    ports:
      - "1880:1880"
    networks:
          - nodered-mosquitto
    volumes:
          - shared-data:/data

  client:
    image: ubuntu:latest
    build: ./clientMqtt/
    networks:
          - nodered-mosquitto

volumes:
  shared-data:
  config:
  log:

networks:
  nodered-mosquitto:
    driver: bridge
